config/routes.rb
SampleApp::Application.routes.draw do
  resources :websites

  resources :posts do
    resources :comments
  end

  resources :links
  
  root 'static_pages#home'
  match '/erase_link',  to: 'static_pages#erase_link',     via: 'get'
  match '/deleteable',  to: 'static_pages#deleteable',     via: 'get'
  match '/help',        to: 'static_pages#help',           via: 'get'
  match '/about',       to: 'static_pages#about',          via: 'get'
  match '/contact',     to: 'static_pages#contact',        via: 'get'
  match '/admin',       to: 'static_pages#admin',          via: 'get'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :commenter, :presence=> true
  validates :body, :presence=> true
end

app/models/post.rb
class Post < ActiveRecord::Base
	default_scope -> { order('created_at DESC') }
	validates :title, :presence =>true

	has_many :comments
end

app/models/website.rb
class Website < ActiveRecord::Base
	validates :link, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:commenter, :body))
    	redirect_to post_path(@post)
    	
	end

	def destroy
		 @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
	end


	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
http_basic_authenticate_with :name => "Anna", :password => "Banana", :except => [:index, :show]

  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.paginate(:page => params[:page], :per_page => 5, :order => "created_at DESC")
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
     @post = Post.find(params[:id])
 
    respond_to do |format|
      format.html  # show.html.erb
      format.json  { render :json => @post }
    end
  end



  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to admin_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit( :title, :content)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@posts=Post.first
  end

  def help
  end

  def about
  end
  
  def contact
  end

  def admin
  end

  def deleteable
    @posts=Post.all
  end

  def erase_link
    @websites=Website.all
  end
  
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  http_basic_authenticate_with :name => "Anna", :password => "Banana", :except => [:index, :show]


  before_action :set_website, only: [:show, :edit, :update, :destroy]

  # GET /websites
  # GET /websites.json
  def index
    @websites = Website.all
  end

  # GET /websites/1
  # GET /websites/1.json
  def show
  end

  # GET /websites/new
  def new
    @website = Website.new
  end

  # GET /websites/1/edit
  def edit
  end

  # POST /websites
  # POST /websites.json
  def create
    @website = Website.new(website_params)

    respond_to do |format|
      if @website.save
        format.html { redirect_to @website, notice: 'Website was successfully created.' }
        format.json { render action: 'show', status: :created, location: @website }
      else
        format.html { render action: 'new' }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /websites/1
  # PATCH/PUT /websites/1.json
  def update
    respond_to do |format|
      if @website.update(website_params)
        format.html { redirect_to @website, notice: 'Website was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /websites/1
  # DELETE /websites/1.json
  def destroy
    @website.destroy
    respond_to do |format|
      format.html { redirect_to websites_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_website
      @website = Website.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def website_params
      params.require(:website).permit( :link, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	 def full_title(page_title)
    base_title = "Human Traffic"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/deleteable_helper.rb
module DeleteableHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  	end

    def sign_out
      self.current_user = nil
      cookies.delete(:remember_token)
    end
    

  	def current_user=(user)
  		@current_user=user
  	end
  	
  	def current_user
  		remember_token=User.encrypt(cookies[:remember_token])
  		@current_user ||=User.find_by(remember_token: remember_token)
  	end

  	def signed_in?
  		!current_user.nil?
  	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/comments/_comment.html.erb
<p>
	<b>Name</b><br>
<%= comment.commenter %>
</p>
 
<p>
  <b>Comment</b><br>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Delete', [comment.post, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

<hr size="3" color="#000000">

app/views/comments/_form.html.erb
<div class="row">
<div class="span6 offset3">


<%= form_for([@post, @post.comments.build]) do |f| %>
  
    <%= f.label :name %><br />
    <%= f.text_field :commenter%>
  
    <%= f.label :body %><br />
    <%= f.text_field :body %>
  </div>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    By Travis Randolph
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to 'Admin', admin_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse" color="white">
        <span class="icon-th-list"></span></a>
      <%= link_to "Human Trafficking", root_path, id: "logo" %>
     
        <div class="nav-collapse collapse">
        <ul class="nav pull-right">
          <li><%= link_to "Posts" , posts_path%></li>
          <li><%= link_to "Helpful Links", websites_path %></li>
           <li><%= link_to "About",   about_path %></li>
          <li><%= link_to "Help",    help_path %></li>
        </ul>
      </div>
      
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"> <%= value%> </div>
        <% end %>
      <%= yield %>
      
    </div>
    <%=render 'layouts/footer' %>
      <%=debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>
<div align="center">
<%= will_paginate @posts, :page_links => false %>
</div>
<br><br>
 <% @posts.each do |post| %> 
 	<div align="center">
        <h4 ><%= post.title %></h4>
    </div>
        <p><%= post.content %></p>
        <%= link_to 'Comment', post %>
        
        <br><br><br>
        <hr color="#000000" size="5">
        <br><br><br>
    <% end %> 

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>



  
<h1><%= @post.title %></h1>


<p>
  <%= @post.content %>
</p>
<br><br><br><br>

<div align = "center">
<h3>Comments</h3>
</div>
<%= render @post.comments %>
<div align = "center">
<h3>Add a comment</h3>
<%= render "comments/form" %>


<%= link_to 'Back', posts_path %>
</div>

app/views/shared/_error_messages.html.erb
<% if @comment.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @comment.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
		This blog was started to help bring about awareness for human trafficing.	
</p>

app/views/static_pages/admin.html.erb
<li><%= link_to 'New Blog Entry', new_post_path %></li>
<br>

<li><%= link_to 'Edit Blog Entry', deleteable_path %></li>
<br>
<li><%= link_to 'New Link', new_website_path%></li>
<br>
<li><%= link_to 'Edit Link', erase_link_path%></li>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
 	Please Contact us at chewebaccaflocka@gmail.com
</p>

app/views/static_pages/deleteable.html.erb
<h1>Posts</h1>


 <% @posts.each do |post| %> 
        <h4><%= post.title %></h4>
 		<%= link_to 'Delete Post', post, :method => :delete, :confirm => "Are you sure?" %> ||
 		<%= link_to 'Edit Blog Entry', edit_post_path(post) %>
        
        <br><br><br>
        <hr color="#000000" size="5">
        <br><br><br>
    <% end %> 

app/views/static_pages/erase_link.html.erb
<h1> Helpful Links</h1>


<% @websites.each do |website| %> 
       	<%= auto_link(website.link) %>
        <%= link_to 'Delete Post', website, :method => :delete, :confirm => "Are you sure?" %> ||
 		<%= link_to 'Edit Link', edit_website_path(website) %>
        
        <br><br><br>
        <hr color="#000000" size="5">
        <br><br><br>
    <% end %> 

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
	If you would like more information about how you can help stop human trafficking, please email us at Anna.Merzi@gmail.com.


	Thank you for your support!
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
	<h1>Human Trafficking</h1>
<h2>Hi! I'm Anna Merzi. I worked to combat the growing problem of human trafficking here in America. These posts are designed to bring awareness to and inform people about human traficking here in the United States</h2>


<h3>
<%= link_to image_tag("help_me.jpg", alt: "Human Traficc"), "http://en.wikipedia.org/wiki/Human_trafficking" %>
</h3>
<div align="left">
<% if @posts!=nil %>
        <h4><%= @posts.title %></h4>
        <p><%= @posts.content %></p>
        
   <% end %>
   <br><br><hr><br>
   <%= link_to "Read the rest of the posts here!", posts_path %>
</div>

  

app/views/websites/_form.html.erb
<div class="row">
<div class="span6 offset3">


<%= form_for(@website) do |f| %>

    <%= f.label :link %><br />
    <%= f.text_field :link%>
  
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/websites/edit.html.erb
<h1>Editing website</h1>

<%= render 'form' %>

<%= link_to 'Show', @website %> |
<%= link_to 'Back', websites_path %>

app/views/websites/index.html.erb
<h1> Helpful Links</h1>


<% @websites.each do |website| %> 
       	<%= auto_link(website.link) %>
        <p><%= website.description %></p>
        
        <br><br><br>
        <hr color="#000000" size="5">
        <br><br><br>
    <% end %> 

app/views/websites/new.html.erb
<h1>New website</h1>

<%= render 'form' %>

<%= link_to 'Back', websites_path %>

app/views/websites/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_website_path(@website) %> |
<%= link_to 'Back', websites_path %>